CREATE TABLE IF NOT EXISTS`post` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(100),
	`url` VARCHAR(120),
	`timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`score` INT NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`)
);