CREATE TABLE IF NOT EXISTS users(
	username VARCHAR(100) NOT NULL,
	PRIMARY KEY(username)
);

CREATE TABLE IF NOT EXISTS posts(
	pId INT NOT NULL AUTO_INCREMENT,
	title VARCHAR(100),
	url VARCHAR(120),
	timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	score INT NOT NULL DEFAULT '0',
	username VARCHAR(100) NOT NULL,
	PRIMARY KEY(pId),
	FOREIGN KEY(username) REFERENCES users(username)
);

CREATE TABLE IF NOT EXISTS votes(
	vId INT NOT NULL AUTO_INCREMENT,
	username VARCHAR(100) NOT NULL,
	pId INT NOT NULL,
	vote INT NOT NULL,
	PRIMARY KEY(vId),
	FOREIGN KEY(username) REFERENCES users(username),
	FOREIGN KEY(pId) REFERENCES posts(pId)
);
